package com.project.Eccomerce.Domain;

public enum AccountStatus {

	PENDING_VERFICATION,    // ACCOUNT IS CREATED, BUT NOT YET VERIFIED
	ACTIVE,					// ACCOUNT IS ACTIVE AND IN GOOD STANDING
	SUSPENDED,				// ACCOUNT IS TEMPORARILY SUSPENDED , POSIBLE DUE TO VIOLATION
	DEACTIVATED,			// ACCOUNT IS DEACTIVATED, USER MAY BE CHOOSEN IT TO DEACTIVE 
	BANNED,					// ACCOUNT IS PERMENTANTLY BANNED DUE TO SERVER VILOATION
	CLOSED					// ACCOUNT IS PERMENTENTLY CLOSED POSSIBLY IT FROM USER REQUEST
}
